server:
  port: 11000
spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:13306/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gms-order

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

management:
  endpoints:
    web:
      exposure:
        include: '*'